required:
- email
properties:
  email:
    type: string
    format: email
    example: joe.smith@a-company.com
  phone:
    $ref: '#/components/schemas/PhoneNumber'
  nationalIdentificationNumber:
    $ref: '#/components/schemas/NationalIdentificationNumber'
  givenName:
    $ref: '#/components/schemas/GivenName'
  additionalName:
    $ref: '#/components/schemas/AdditionalName'
  familyName:
    $ref: '#/components/schemas/FamilyName'
