properties:
  id:
    type: string
    example: ap_0462a90c-fd56-4820-b8d4-28f252629c2c
  source:
    type: string
    format: uri
    example: https://api.qred.com/loans/v1/applications/ap_0462a90c-fd56-4820-b8d4-28f252629c2c/_source
  url:
    type: string
    format: uri
    example: https://api.qred.com/loans/v1/applications/ap_0462a90c-fd56-4820-b8d4-28f252629c2c
