properties:
  id:
    type: string
    example: ap_0462a90c-fd56-4820-b8d4-28f252629c2c
  url:
    type: string
    format: uri
    example: https://api.qred.com/loans/v1/applications/ap_0462a90c-fd56-4820-b8d4-28f252629c2c
  userLandingPage:
    type: string
    format: uri
    example: https://qred.com/en/thanks-for-the-application?partner=partner&id=ap_0462a90c-fd56-4820-b8d4-28f252629c2c
