allOf:
  - $ref: '#/components/schemas/ApplicationDecision'
  - type: object
    properties:
      amount:
        type: number
      term:
        type: number
      campaign:
        type: string
example:
  status: Approved
  amount: 5000
  term: 12
  campaign: Spring Campaign
