required:
- amount
- organization
- applicant
properties:
  amount:
    $ref: '#/components/schemas/Amount'
  promoCode:
    $ref: '#/components/schemas/PromoCode'
  term:
    $ref: '#/components/schemas/LoanTerm'
  purposeOfLoan:
    $ref: '#/components/schemas/PurposeOfLoan'
  organization:
    $ref: '#/components/schemas/SimpleOrganization'
  applicant:
    $ref: '#/components/schemas/SimpleApplicant'
  files:
    $ref: '#/components/schemas/Base64Files'
  $type:
    type: string
    example: simple
    description: Note that `$type` must be `full` in order to send in further information.