type: object
properties:
  errors:
    type: array
    items:
      $ref: '#/components/schemas/ApplicationErrorResponseItem'
example:
  { "errors":[{"property":"amount", "description": "Amount is a required field", "code": "NotNull"},
   {"property":"organization.organizationId", "description": "organizationId is a required field", "code": "NotNull"},
   {"property":"applicant.email", "description": "email is a required field", "code": "NotNull"}
  ] }