allOf:
  - $ref: '#/components/schemas/ApplicationOrganization'
  - type: object
    required:
    - $type
    properties:
      numberOfEmployees:
        type: number
        example: 5
        description: Number of full time employees.
      currentMonthlyTurnover:
        type: string
        example: 100000
        description: >-
          ### Short

          Turnover for last month in national currency. 
          
          ### Abbreviation

          Expected to be the full amount, i.e. 1 000 implies 1 thousand in the local currency.

          ### Turnover currency code?

          Note that the currency is specified when issued API key.
      owners:
        type: array
        items:
          $ref: '#/components/schemas/OrganizationOwner'
      iban:
        type: string
        example: DE89 3704 0044 0532 0130 00
        description: >
          International Bank Account Number. The company bank account for receiving out payment. 
      $type:
        type: string
        example: full
        description: Note that `$type` must be `full` in order to send in further information.