required:
- amount
- organization
- applicant
properties:
  amount:
    type: number
    example: 15000.00
    description: >-
      ### Amount

      The amount in local currency that the company wants to borrow. 
      
      ### Abbreviation

      Expected to be the full amount, i.e. 1 000 implies 1 thousand in the local currency.

      ### Currency code of amount?

      Note that the currency is specified when issued API key.
  promoCode:
    type: string
    example: SOMECAMPAIGN123
    description: >-
      Promo code used to give the customer a discount or extra benefits.
  term:
    type: number
    example: 12
    description: Loan term number of months
  purposeOfLoan:
    type: string
    example: "I need to increase liquidity due to upcoming costs associated with participation in branch conference"
    description: >-
      Company explains why they need the business loan
  organization:
    $ref: '#/definitions/ApplicationOrganization'
  applicant:
    $ref: '#/definitions/ApplicationApplicant'
  files:
    type: array
    items:
      $ref: '#/definitions/UploadBase64File'
    description: Here you can supply additional files such as images, pdfs or company specify formats in order to get a faster qualification for your customer.
