required:
- email
properties:
  email:
    type: string
    format: email
    example: joe.smith@a-company.com
  phone:
    $ref: '#/definitions/PhoneNumber'
  nationalIdentificationNumber:
    $ref: '#/definitions/NationalIdentificationNumber'
  givenName:
    $ref: '#/definitions/GivenName'
  additionalName:
    $ref: '#/definitions/AdditionalName'
  familyName:
    $ref: '#/definitions/FamilyName'
