properties:
  type: 
    $ref: '#/definitions/ApplicationDecisionType'  
  rejectReason:
    type: string
example:
  type: Denied
  rejectReason: Due to previous problems with payments we regret that we have to reject the application.
  