required:
- email
properties:
  email:
    type: string
    format: email
    example: joe.smith@a-company.com
  mobile:
    type: string
    example: "408-867-5309"
    description: "The mobile phone number."
  personalId:
    $ref: '#/definitions/PersonalId'
  givenName:
    $ref: '#/definitions/GivenName'
  additionalName:
    $ref: '#/definitions/AdditionalName'
  familyName:
    $ref: '#/definitions/FamilyName'
