required:
- organizationId

properties:
  vatIdentificationNumber:
    type: string
    example: "SE2344473928"
    description: >
      The VAT identifier is used to identify organizations in various countries.
      In Sweden that would be a prefixed organization number. In Denmark you have prefixed CVR-number. 
      See [VAT identification number](https://en.wikipedia.org/wiki/VAT_identification_number) for more information.
  email:
    type: string
    format: email
    example: invoice@a-company.com
    description: Company email 
  phone:
    type: string
    example: "+4688675309"
    description: >
      The phone number. Note that the phone number might not be sent as a number,
      see [E.161](https://en.wikipedia.org/wiki/E.161). 
      We prefer [E.164](https://en.wikipedia.org/wiki/E.164).
  url:
    type: string
    example: "http://www.a-company.com"
    description: "Url to the organization site."
