required:
- organizationId

properties:
  organizationId:
    type: string
    example: "SE2344473928"
    description: "Organization identifier. In Sweden that would be organization number. In Denmark you have CVR-number. Internationally you also have duns and isicV4."
  email:
    type: string
    format: email
    example: invoice@a-company.com
    description: Company email 
  telephone:
    type: string
    example: "408-867-5309"
    description: "The telephone number."
  url:
    type: string
    example: "http://www.a-company.com"
    description: "Url to the organization site."
