required:
- organizationId

properties:
  organizationId:
    type: string
    example: "SE2344473928"
    description: "Organization identifier. In Sweden that would be organization number. In Denmark you have CVR-number. Internationally you also have duns and isicV4."
  email:
    type: string
    format: email
    example: contact@a-company.com
  telephone:
    type: string
    example: "408-867-5309"
    description: "The telephone number."
  url:
    type: string
    example: "http://www.a-company.com"
    description: "Url to the organization site."
  currentMonthlyTurnover:
    type: string
    example: 100000
    description: "Turnover for last month in national currency. Expected to be the full amount, i.e. 1 000 000 SEK implies 1 million SEK."