allOf:
  - $ref: '#/definitions/ApplicationDecision'
  - type: object
    properties:
      amount:
        type: number
      term:
        type: number
      campaign:
        type: string
      offerUrl:
        type: string
        description: Url for the user to see and accept the offer given by Qred
example:
  type: Approved
  amount: 5000
  term: 12
  campaign: Spring Campaign
  offerUrl: https://qred.com/link-to-offer?id=offer-id
