swagger: '2.0'
schemes:
  - https
host: api.qred.com
basePath: /loans/v1
info:
  description: >
    This is the Connect to Qred API

    # Introduction

    The purpose of this API is to give companies and developers the ability to help their customers with loan applications.

  version: 0.1.0
  title: Connect to Qred
  termsOfService: 'https://connect.qred.com/terms/'
  contact:
    email: techsupport@qred.com
    url: 'https://connect.qred.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://qred.com/img/qred-logo-mobile-green.png'
securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: api_key
tags:
- name: developers
  description: Operations available to regular developers

