#  /applications/{id}:
 get:
    summary: Get loan application
    description: Get information about loan application from Qred
    tags:
      - developers
    parameters:
    - name: applicationid
      in: path
      description: The id of the application
      required: true
      type: string
    produces:
    - application/json
    responses:
      200:
        description: Found application with id
        schema:
          $ref: '#/definitions/ApplicationDecisionApproved'
      210:
        description: Found application with id
        schema:
          $ref: '#/definitions/ApplicationDecisionManualProcess'
      211:
        description: Found application with id
        schema:
          $ref: '#/definitions/ApplicationDecisionRejected'
      404:
        description: Application not found
    security:
      - api_key: []
 