get:
  summary: Status of loan application
  operationId: get
  description: Get summary information about loan application from Qred
  tags:
    - applications
  parameters:
  - name: applicationId
    in: path
    description: The id of the application
    required: true
    schema: 
      type: string
      pattern: "ap_[^/]+"
  responses:
    200:
      description: Found application with id
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationDecisionApproved'
    210:
      description: Found application with id
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationDecisionManualProcess'
    211:
      description: Found application with id
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationDecisionRejected'
    404:
      description: Application not found
  security:
    - JWT: []
 