
post:
  tags:
  - applications
  summary: Add loan application
  operationId: add
  description: Send a loan application to Qred
  consumes:
  - application/json
  produces:
  - application/json
  parameters:
  - in: body
    name: application
    description: Application to add
    schema:
      $ref: '#/definitions/ApplicationRequest'
  responses:
    201:
      description: item created
      schema:
        $ref: '#/definitions/ApplicationCreateResponse'
    400:
      description: invalid input, object invalid
      schema:
       $ref: '#/definitions/ApplicationErrorResponse'
  security:
    - api_key: []
