theme:
  colors:
    primary:
      main: '#050F09'
  logo:
    maxWidth: '200px'
    marginTop: '24px'
  menu:
    backgroundColor: '#242C7A'
    textColor: '#ffffff'
  rightPanel:
    backgroundColor: '#ffffff'
  codeSample:
    backgroundColor: '#070812'
  typography:
    links:
      color: '#ffffff'